name: Terraform Apply

permissions:
  id-token: write
  contents: read
## ==============================================
## Section 1: SCHEDULING AND TRIGGERS
## ==============================================
on:
  # Trigger on PR events
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main      # PR to main
      - develop   # PR to develop
      - '**'      # Any other PR
  
  # Trigger on push to dev branches
  push:
    branches:
      - 'dev/**'  # Push to dev/* branches = dev deployment
  
  # Manual trigger via GitHub UI (dev only)
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev only for manual trigger)'
        required: true
        type: choice
        options:
          - dev
        default: dev


# Environment variables
env:
  TF_VERSION: '1.5.7'
  
jobs:
  # Job 1: Plan
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    
    # Set environment based on trigger
    env:
      ENVIRONMENT: ${{ 
        github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
        github.event_name == 'schedule' && 'prod' ||
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main') && 'prod' ||
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'develop') && 'stage' ||
        (github.event_name == 'pull_request' && !github.event.pull_request.merged && github.base_ref == 'main') && 'prod' ||
        (github.event_name == 'pull_request' && !github.event.pull_request.merged && github.base_ref == 'develop') && 'stage' ||
        (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dev/')) && 'dev' ||
        'dev' }}
    
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      plan-exitcode: ${{ steps.plan.outputs.exitcode }}
    
    defaults:
      run:
        shell: bash
        working-directory: environments/${{ env.ENVIRONMENT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      ## ==============================================
      ## Section 2: GOOGLE CLOUD AUTHENTICATION WITH WIF
      ## ==============================================
      # Set WIF provider based on environment
      - name: Set WIF Provider
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "dev" ]]; then
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_DEV_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          elif [[ "${{ env.ENVIRONMENT }}" == "stage" ]]; then
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_STAGE_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          else
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_PROD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          fi
          echo "SERVICE_ACCOUNT=terraform-${{ env.ENVIRONMENT }}@${{ secrets.GCP_PROJECT_PREFIX }}-${{ env.ENVIRONMENT }}.iam.gserviceaccount.com" >> $GITHUB_ENV
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: 'access_token'
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      ## ==============================================
      ## Section 3: TERRAFORM CHECKS AND PLAN
      ## ==============================================
      
      # Check formatting
      - name: Terraform Format Check
        id: fmt
        run: |
          terraform fmt -check -recursive
        continue-on-error: true
      
      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: |
          terraform init -no-color
      
      # Validate configuration
      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color
      
      # Generate plan
      - name: Terraform Plan
        id: plan
        env:
          # Map GitHub Secrets to Terraform variables based on environment
          # GitHub stores secrets with uppercase environment names
          TF_VAR_project_id: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_PROJECT_ID || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_PROJECT_ID || secrets.TF_VAR_PROD_PROJECT_ID }}
          TF_VAR_region: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_REGION || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_REGION || secrets.TF_VAR_PROD_REGION }}
          TF_VAR_zone: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ZONE || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ZONE || secrets.TF_VAR_PROD_ZONE }}
          # Optional variables - use empty defaults if not set
          TF_VAR_dataset_owners: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_OWNERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_OWNERS) || secrets.TF_VAR_PROD_DATASET_OWNERS || '[]' }}
          TF_VAR_dataset_writers: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_WRITERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_WRITERS) || secrets.TF_VAR_PROD_DATASET_WRITERS || '[]' }}
          TF_VAR_dataset_readers: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_READERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_READERS) || secrets.TF_VAR_PROD_DATASET_READERS || '[]' }}
          TF_VAR_ml_team_group: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ML_TEAM_GROUP) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ML_TEAM_GROUP) || secrets.TF_VAR_PROD_ML_TEAM_GROUP || '' }}
          TF_VAR_analysts_group: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ANALYSTS_GROUP) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ANALYSTS_GROUP) || secrets.TF_VAR_PROD_ANALYSTS_GROUP || '' }}
        run: |
          set +e
          terraform plan -no-color -out=tfplan -detailed-exitcode
          exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          
          # Exit codes: 0 = no changes, 1 = error, 2 = changes present
          if [ $exitcode -eq 1 ]; then
            echo "Terraform plan failed with error"
            exit 1
          fi
          exit 0
      
      # Save plan for apply job (only if plan succeeded)
      - name: Upload Plan
        if: steps.plan.outputs.exitcode != '1'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ env.ENVIRONMENT }}
          path: environments/${{ env.ENVIRONMENT }}/tfplan
          retention-days: 1
      
      # Comment on PR if this is from a pull request
      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan for ${{ env.ENVIRONMENT }} environment</summary>
            
            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>
            
            **Target Environment:** \`${{ env.ENVIRONMENT }}\`
            **Plan shows changes that will be applied when this PR is merged**
            
            *Triggered by: @${{ github.actor }}, Action: ${{ github.event_name }}*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  
  # Job 2: Apply (only runs if plan succeeds and conditions are met)
  terraform-apply:
    name: "Terraform Apply"
    needs: terraform-plan
    runs-on: ubuntu-latest
    
    # Only run apply for specific conditions
    if: |
      needs.terraform-plan.outputs.plan-exitcode == '2' &&
      (
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main') ||
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'develop') ||
        (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dev/')) ||
        (github.event_name == 'workflow_dispatch') ||
        (github.event_name == 'schedule')
      )
    
    env:
      ENVIRONMENT: ${{ needs.terraform-plan.outputs.environment }}
    
    defaults:
      run:
        shell: bash
        working-directory: environments/${{ env.ENVIRONMENT }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      # Re-authenticate (new job needs fresh auth)
      # Set WIF provider based on environment
      - name: Set WIF Provider
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "dev" ]]; then
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_DEV_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          elif [[ "${{ env.ENVIRONMENT }}" == "stage" ]]; then
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_STAGE_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          else
            echo "WIF_PROVIDER=projects/${{ secrets.GCP_PROD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          fi
          echo "SERVICE_ACCOUNT=terraform-${{ env.ENVIRONMENT }}@${{ secrets.GCP_PROJECT_PREFIX }}-${{ env.ENVIRONMENT }}.iam.gserviceaccount.com" >> $GITHUB_ENV
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: 'access_token'
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      # Download the plan
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ env.ENVIRONMENT }}
          path: environments/${{ env.ENVIRONMENT }}
      
      # Initialize Terraform
      - name: Terraform Init
        run: |
          terraform init -no-color
      
      # Apply the plan
      - name: Terraform Apply
        env:
          # Map GitHub Secrets to Terraform variables based on environment
          # GitHub stores secrets with uppercase environment names
          TF_VAR_project_id: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_PROJECT_ID || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_PROJECT_ID || secrets.TF_VAR_PROD_PROJECT_ID }}
          TF_VAR_region: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_REGION || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_REGION || secrets.TF_VAR_PROD_REGION }}
          TF_VAR_zone: ${{ env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ZONE || env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ZONE || secrets.TF_VAR_PROD_ZONE }}
          # Optional variables - use empty defaults if not set
          TF_VAR_dataset_owners: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_OWNERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_OWNERS) || secrets.TF_VAR_PROD_DATASET_OWNERS || '[]' }}
          TF_VAR_dataset_writers: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_WRITERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_WRITERS) || secrets.TF_VAR_PROD_DATASET_WRITERS || '[]' }}
          TF_VAR_dataset_readers: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_DATASET_READERS) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_DATASET_READERS) || secrets.TF_VAR_PROD_DATASET_READERS || '[]' }}
          TF_VAR_ml_team_group: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ML_TEAM_GROUP) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ML_TEAM_GROUP) || secrets.TF_VAR_PROD_ML_TEAM_GROUP || '' }}
          TF_VAR_analysts_group: ${{ (env.ENVIRONMENT == 'dev' && secrets.TF_VAR_DEV_ANALYSTS_GROUP) || (env.ENVIRONMENT == 'stage' && secrets.TF_VAR_STAGE_ANALYSTS_GROUP) || secrets.TF_VAR_PROD_ANALYSTS_GROUP || '' }}
        run: |
          terraform apply -no-color -auto-approve tfplan
      
      # Output summary
      - name: Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Event**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Successfully applied" >> $GITHUB_STEP_SUMMARY